services:
- type: web
  name: next-js
  runtime: node
  plan: starter
  buildCommand: npm install; npm run build
  startCommand: yarn start
  autoDeploy: false
  envVars:
  - key: NODE_ENV
    value: production